### ISSUE TITLE
[Bug]: CI should not cancel the build on push

### ISSUE THREAD

**Issue by vgvassilev** [compiler-research/CppInterOp#597]
### Description of bug

We should have something like:
```yaml
  # Avoids canceling push to main of the same commit (github.sha) but will
  # cancel running builds when you update the source branch of a PR.
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
```

According to stackoverflow this won't cancel merged PRs while it will cancel a push to a PR branch...
